
services:
  open-agbot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: open-agbot-main
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 3000M
    restart: always
