# Configuration Settings for U-blox F9P
ublox_gps_node:
  ros__parameters:
    debug: 1                    # Range 0-4 (0 means no debug statements will print)

    # device: /dev/ttyACM0      # This will be overridden by the launch file
    frame_id: gnss

    uart1:
      baudrate: 921600

    config_on_startup: false    # If false, the node will not override configurations of the device on startup
                                # Device should be configured with u-center and configurations should be saved in flash

    # Enable u-blox message publishers
    publish:
      all: true
      nav:
        all: true
      rxm:
        all: true
